apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: git-dir-appset
  namespace: argocd
spec:
  # goTemplate: true
  # goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/ghorbani-ali/ArgoCD-Demo.git
        revision: main
        directories:
          - path: "configs/cluster/engineering/*"
          - path: "configs/cluster/engineering/prod"
            exclude: true
  template:
    metadata:
      name: '{{ path[2] }}-{{ path.basename }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/ghorbani-ali/ArgoCD-Demo.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ path.basename }}-namespace'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  templatePatch: |
    spec:
       source:
         repoURL: registry-1.docker.io/bitnamicharts
         chart: nginx
         targetRevision: 18.2.5
       destination:
         server: https://kubernetes.default.svc
         namespace: default