apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: env-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            cluster: https://dev-cluster.example.com
          - env: staging
            cluster: https://staging-cluster.example.com
          - env: prod
            cluster: https://prod-cluster.example.com
  template:
    metadata:
      name: '{{.env}}-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/example/my-app.git
        targetRevision: main
        path: 'manifests/{{.env}}'
      destination:
        server: '{{.cluster}}'
        namespace: '{{.env}}-namespace'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true