apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: list-appset
  namespace: argocd
spec:
  # goTemplate: true
  # goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - env: dev
            cluster: https://dev-cluster.example.com
          - env: staging
            cluster: https://staging-cluster.example.com
          - env: prod
            cluster: https://prod-cluster.example.com
  template:
    metadata:
      name: '{{ env }}-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/ghorbani-ali/ArgoCD-Demo.git
        targetRevision: main
        path: 'manifests/{{ env }}'
      destination:
        server: '{{ cluster }}'
        namespace: '{{ env }}-namespace'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  templatePatch: |
    spec:
       source:
         repoURL: registry-1.docker.io/bitnamicharts
         chart: nginx
         targetRevision: 18.2.5
       destination:
         server: https://kubernetes.default.svc
         namespace: default