apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: matrix-list-git
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/ghorbani-ali/ArgoCD-Demo.git
              revision: HEAD
              files:
                - path: "configs/cluster/engineering/**/config.json"
          - list:
              elements:
                - env: "{{ index .path.segments 3 }}"
                  cluster: "{{ .cluster.address }}"
  template:
    metadata:
      name: '{{ .env }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/ghorbani-ali/ArgoCD-Demo.git
        targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .cluster.address }}-namespace'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  templatePatch: |
    spec:
       source:
         repoURL: registry-1.docker.io/bitnamicharts
         chart: nginx
         targetRevision: 18.2.5
         helm:
          parameters:
          - name: "service.type"
            value: ClusterIP
       destination:
        server: https://kubernetes.default.svc
        namespace: default