apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: github-appset
  namespace: argocd
spec:
  generators:
    - scmProvider:
        github:
          organization: my-org
          tokenRef:
            secretName: github-token
            key: token
          api: https://api.github.com
  template:
    metadata:
      name: '{{repository}}'
    spec:
      project: default
      source:
        repoURL: '{{url}}'
        targetRevision: main
        path: manifests
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{repository}}-namespace'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true