apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pr-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - pullRequest:
        gitlab:
          repo: https://gitlab.com
          project: "66637646"
          tokenRef:
            secretName: gitlab-token
            key: token
          labels:
          - preview
          pullRequestState: opened
        requeueAfterSeconds: 5
  template:
    metadata:
      name: 'pr-{{ .number }}'
    spec:
      project: default
      source:
        repoURL: https://gitlab.com/ghorbaniali/argo-test.git
        targetRevision: '{{ .head_sha }}'
        path: manifests
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  templatePatch: |
    spec:
       source:
         repoURL: registry-1.docker.io/bitnamicharts
         chart: nginx
         targetRevision: 18.2.5
         helm:
          parameters:
          - name: "service.type"
            value: ClusterIP
       destination:
         server: https://kubernetes.default.svc
         namespace: default