apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: github-appset
  namespace: argocd
spec:
  generators:
    - scmProvider:
        filters:
          - repositoryMatch: "argo-test"
            branchMatch: main
        gitlab:
          group: "55115479"
          api: https://gitlab.com
          includeSharedProjects: false
          tokenRef:
            secretName: gitlab-token
            key: token
  template:
    metadata:
      name: '{{ .repository }}'
    spec:
      project: default
      source:
        repoURL: '{{ .url }}'
        targetRevision: main
        path: manifests
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .repository }}-namespace'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  templatePatch: |
    spec:
       source:
         repoURL: registry-1.docker.io/bitnamicharts
         chart: nginx
         targetRevision: 18.2.5
       destination:
         server: https://kubernetes.default.svc
         namespace: default